--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2 (Postgres.app)
-- Dumped by pg_dump version 16.2 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: lookup_parseddata; Type: TABLE; Schema: public; Owner: raofamily
--

CREATE TABLE public.lookup_parseddata (
    id bigint NOT NULL,
    file_name character varying NOT NULL,
    "MPAN_Core" character varying(13) NOT NULL,
    validation_status character varying(1) NOT NULL,
    serial_number character varying(10) NOT NULL,
    reading_type character varying(1) NOT NULL
);


ALTER TABLE public.lookup_parseddata OWNER TO raofamily;

--
-- Name: lookup_parseddata_id_seq; Type: SEQUENCE; Schema: public; Owner: raofamily
--

ALTER TABLE public.lookup_parseddata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lookup_parseddata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lookup_registerreadings; Type: TABLE; Schema: public; Owner: raofamily
--

CREATE TABLE public.lookup_registerreadings (
    id bigint NOT NULL,
    meter_id character varying(2) NOT NULL,
    reading_date_time timestamp with time zone NOT NULL,
    register_reading numeric(9,1) NOT NULL,
    reading_method character varying(1) NOT NULL,
    reading_flag character varying(1) NOT NULL,
    reading_reason_code character varying(2) NOT NULL,
    reading_status character varying(2) NOT NULL,
    site_visit_check_code character varying(2) NOT NULL,
    mpan_id bigint NOT NULL
);


ALTER TABLE public.lookup_registerreadings OWNER TO raofamily;

--
-- Name: lookup_registerreadings_id_seq; Type: SEQUENCE; Schema: public; Owner: raofamily
--

ALTER TABLE public.lookup_registerreadings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lookup_registerreadings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: lookup_parseddata; Type: TABLE DATA; Schema: public; Owner: raofamily
--

COPY public.lookup_parseddata (id, file_name, "MPAN_Core", validation_status, serial_number, reading_type) FROM stdin;
395	test_file.txt	1200023305967	V		
\.


--
-- Data for Name: lookup_registerreadings; Type: TABLE DATA; Schema: public; Owner: raofamily
--

COPY public.lookup_registerreadings (id, meter_id, reading_date_time, register_reading, reading_method, reading_flag, reading_reason_code, reading_status, site_visit_check_code, mpan_id) FROM stdin;
\.


--
-- Name: lookup_parseddata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: raofamily
--

SELECT pg_catalog.setval('public.lookup_parseddata_id_seq', 395, true);


--
-- Name: lookup_registerreadings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: raofamily
--

SELECT pg_catalog.setval('public.lookup_registerreadings_id_seq', 304, true);


--
-- Name: lookup_parseddata lookup_parseddata_pkey; Type: CONSTRAINT; Schema: public; Owner: raofamily
--

ALTER TABLE ONLY public.lookup_parseddata
    ADD CONSTRAINT lookup_parseddata_pkey PRIMARY KEY (id);


--
-- Name: lookup_registerreadings lookup_registerreadings_pkey; Type: CONSTRAINT; Schema: public; Owner: raofamily
--

ALTER TABLE ONLY public.lookup_registerreadings
    ADD CONSTRAINT lookup_registerreadings_pkey PRIMARY KEY (id);


--
-- Name: lookup_registerreadings_mpan_id_f00fda72; Type: INDEX; Schema: public; Owner: raofamily
--

CREATE INDEX lookup_registerreadings_mpan_id_f00fda72 ON public.lookup_registerreadings USING btree (mpan_id);


--
-- Name: lookup_registerreadings lookup_registerreadi_mpan_id_f00fda72_fk_lookup_pa; Type: FK CONSTRAINT; Schema: public; Owner: raofamily
--

ALTER TABLE ONLY public.lookup_registerreadings
    ADD CONSTRAINT lookup_registerreadi_mpan_id_f00fda72_fk_lookup_pa FOREIGN KEY (mpan_id) REFERENCES public.lookup_parseddata(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

