# Generated by Django 5.0.4 on 2024-04-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField()),
                ('MPAN_Core', models.IntegerField()),
                ('validation_status', models.CharField(max_length=1)),
                ('serial_number', models.CharField(max_length=10)),
                ('reading_status', models.CharField(max_length=1)),
                ('meter_id', models.CharField(max_length=2)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=9)),
                ('reading_method', models.CharField(max_length=1)),
                ('reading_flag', models.CharField(max_length=1)),
            ],
        ),
    ]
