# Generated by Django 5.0.4 on 2024-04-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parseddata',
            name='MPAN_Core',
            field=models.CharField(max_length=13),
        ),
    ]
