# Generated by Django 5.0.4 on 2024-04-28 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0002_alter_parseddata_mpan_core'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parseddata',
            old_name='reading_flag',
            new_name='reading_type',
        ),
        migrations.RemoveField(
            model_name='parseddata',
            name='meter_id',
        ),
        migrations.RemoveField(
            model_name='parseddata',
            name='reading_date_time',
        ),
        migrations.RemoveField(
            model_name='parseddata',
            name='reading_method',
        ),
        migrations.RemoveField(
            model_name='parseddata',
            name='reading_status',
        ),
        migrations.RemoveField(
            model_name='parseddata',
            name='register_reading',
        ),
        migrations.CreateModel(
            name='RegisterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=2)),
                ('reading_date_time', models.DateTimeField()),
                ('register_reading', models.DecimalField(decimal_places=1, max_digits=9)),
                ('reading_method', models.CharField(max_length=1)),
                ('reading_flag', models.CharField(max_length=1)),
                ('reading_reason_code', models.CharField(max_length=2)),
                ('reading_status', models.CharField(max_length=2)),
                ('site_visit_check_code', models.CharField(max_length=2)),
                ('mpan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lookup.parseddata')),
            ],
        ),
    ]
