# Generated by Django 5.0.4 on 2024-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0003_rename_reading_flag_parseddata_reading_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerreadings',
            name='reading_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
