# Generated by Django 5.0.4 on 2024-04-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0005_alter_registerreadings_reading_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerreadings',
            name='reading_date_time',
            field=models.DateTimeField(),
        ),
    ]
